DROP TABLE PRODUS;
DROP TABLE CATEGORIE;
DROP TABLE DISTRIBUITOR;
DROP TABLE FACTURA_FISCALA;
DROP TABLE COMANDA;
DROP TABLE FIRMA_CURIERAT;
DROP TABLE CLIENT;
DROP SEQUENCE ID_CLIENT_SEQ;
DROP SEQUENCE ID_CURIER_SEQ;
DROP SEQUENCE ID_COMANDA_SEQ;
DROP SEQUENCE ID_FACTURA_SEQ;
DROP SEQUENCE ID_DISTRIBUITOR_SEQ;
DROP SEQUENCE ID_MATERIAL_SEQ;
DROP SEQUENCE ID_BIJUTERIE_SEQ;

CREATE SEQUENCE ID_CLIENT_SEQ
    INCREMENT BY 50
    START WITH 1000
    MAXVALUE 1999;

CREATE SEQUENCE ID_CURIER_SEQ
    INCREMENT BY 35
    START WITH 2000
    MAXVALUE 2999;
    
CREATE SEQUENCE ID_COMANDA_SEQ
    INCREMENT BY 25
    START WITH 3000
    MAXVALUE 3999;
    
CREATE SEQUENCE ID_FACTURA_SEQ
    INCREMENT BY 50
    START WITH 4000
    MAXVALUE 4999;
    
CREATE SEQUENCE ID_DISTRIBUITOR_SEQ
    INCREMENT BY 50
    START WITH 5000
    MAXVALUE 5999;
    
CREATE SEQUENCE ID_MATERIAL_SEQ
    INCREMENT BY 50
    START WITH 6000
    MAXVALUE 6999;
    
CREATE SEQUENCE ID_BIJUTERIE_SEQ
    INCREMENT BY 50
    START WITH 7000
    MAXVALUE 7999;
    
CREATE TABLE CLIENT(
    ID_CLIENT NUMBER(4),
    NUME VARCHAR2(15) CONSTRAINT NUME_NN NOT NULL,
    PRENUME VARCHAR2(15) CONSTRAINT PRENUME_NN NOT NULL,
    ORAS VARCHAR2(15) CONSTRAINT ORAS_NN NOT NULL,
    EMAIL VARCHAR2(20) CONSTRAINT EMAIL_NN NOT NULL,
    USERNAME VARCHAR2(20),
    PAROLA VARCHAR2(15),
    CONSTRAINT CLIENT_ID_CLIENT_PK PRIMARY KEY(ID_CLIENT),
    CONSTRAINT CLIENT_CHK_PAROLA CHECK (LENGTH(PAROLA) >= 6),
    CONSTRAINT CLIENT_CHK_USERNAME CHECK (LENGTH(USERNAME) >= 6),
    CONSTRAINT CLIENT_U_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CLIENT_U_USERNAME UNIQUE (USERNAME)
    );

CREATE TABLE FIRMA_CURIERAT(
    ID_CURIER NUMBER(4),
    ORAS_CURIER VARCHAR2(15) CONSTRAINT ORAS_CURIER_NN NOT NULL,
    NUME_CURIER VARCHAR2(15) CONSTRAINT NUME_CURIER_NN NOT NULL,
    TELEFON_CURIER VARCHAR2(10) CONSTRAINT TELEFON_CURIER_NN NOT NULL,
    CONSTRAINT FIRMA_CURIERAT_ID_CURIER_PK PRIMARY KEY(ID_CURIER),
    CONSTRAINT FIRMA_CURIERAT_CHK_TEL CHECK (LENGTH(TELEFON_CURIER) = 10),
    CONSTRAINT FIRMA_CURIERAT_U_TEL UNIQUE (TELEFON_CURIER)
    );

CREATE TABLE COMANDA(
    ID_COMANDA NUMBER(4),
    DATA_COMANDA DATE CONSTRAINT DATA_COMANDA_NN NOT NULL,
    DATA_LIVRARE DATE CONSTRAINT DATA_LIVRARE_NN NOT NULL,
    PRET_TOTAL NUMBER(3) CONSTRAINT PRET_TOTAL_NN NOT NULL,
    INFORMATII_ADITIONALE VARCHAR(100),
    ID_CLIENT NUMBER(4),
    ID_CURIER NUMBER(4),
    CONSTRAINT COMANDA_ID_COMANDA_PK PRIMARY KEY(ID_COMANDA),
    CONSTRAINT COMANDA_ID_CLIENT_FK FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT) ON DELETE CASCADE,
    CONSTRAINT COMANDA_ID_CURIER_FK FOREIGN KEY(ID_CURIER) REFERENCES FIRMA_CURIERAT(ID_CURIER) ON DELETE CASCADE
    );

CREATE TABLE FACTURA_FISCALA(
    ID_FACTURA NUMBER(4),
    CUI VARCHAR2(12) CONSTRAINT CUI_NN NOT NULL,
    NUME_FIRMA VARCHAR2(20) CONSTRAINT NUME_FIRMA_NN NOT NULL,
    ORAS_FIRMA VARCHAR2(15) CONSTRAINT ORAS_FIRMA_NN NOT NULL,
    ID_COMANDA NUMBER(4),
    CONSTRAINT FACTURA_FISCALA_ID_FACTURA_PK PRIMARY KEY(ID_FACTURA),
    CONSTRAINT FACTURA_FISCALA_ID_COMANDA_FK FOREIGN KEY(ID_COMANDA) REFERENCES COMANDA(ID_COMANDA) ON DELETE CASCADE
    );

CREATE TABLE DISTRIBUITOR(
    ID_DISTRIBUITOR NUMBER(4),
    ORAS_DISTRIBUITOR VARCHAR2(15) CONSTRAINT ORAS_DISTRIBUITOR_NN NOT NULL,
    NUME_DISTRIBUITOR VARCHAR2(50) CONSTRAINT NUME_DISTRIBUITOR_NN NOT NULL,
    TELEFON_DISTRIBUITOR VARCHAR2(10) CONSTRAINT TEL_DISTRIBUITOR_NN NOT NULL,
    CONSTRAINT DISTRIBUITOR_ID_DISTR_PK PRIMARY KEY(ID_DISTRIBUITOR),
    CONSTRAINT DISTRIBUITOR_CHK_TEL CHECK (LENGTH(TELEFON_DISTRIBUITOR) = 10),
    CONSTRAINT DISTRIBUITOR_U_TEL UNIQUE (TELEFON_DISTRIBUITOR)
    );

CREATE TABLE CATEGORIE(
    ID_MATERIAL NUMBER(4) ,
    NUME_CATEGORIE VARCHAR2(15) CONSTRAINT NUME_CATEGORIE_NN NOT NULL,
    CONSTRAINT CATEGORIE_ID_MATERIAL_PK PRIMARY KEY(ID_MATERIAL)
    );

CREATE TABLE PRODUS(
    ID_BIJUTERIE NUMBER(4),
    NUME_PRODUS VARCHAR2(50) CONSTRAINT NUME_PRODUS_NN NOT NULL,
    PRET_PRODUS NUMBER(3) CONSTRAINT PRET_PRODUS_NN NOT NULL,
    NUMAR_CARATE NUMBER(2),
    ID_COMANDA NUMBER(4),
    ID_DISTRIBUITOR NUMBER(4),
    ID_MATERIAL NUMBER(4),
    CONSTRAINT PRODUS_ID_BIJUTERIE_PK PRIMARY KEY(ID_BIJUTERIE),
    CONSTRAINT PRODUS_ID_COMANDA_FK FOREIGN KEY(ID_COMANDA) REFERENCES COMANDA(ID_COMANDA) ON DELETE SET NULL,
    CONSTRAINT PRODUS_ID_DISTRIBUITOR_FK FOREIGN KEY(ID_DISTRIBUITOR) REFERENCES DISTRIBUITOR(ID_DISTRIBUITOR) ON DELETE CASCADE,
    CONSTRAINT PRODUS_ID_MATERIAL_FK FOREIGN KEY(ID_MATERIAL) REFERENCES CATEGORIE(ID_MATERIAL) ON DELETE CASCADE,
    CONSTRAINT PRODUS_U_NUME UNIQUE (NUME_PRODUS)
    );

INSERT INTO CLIENT VALUES(ID_CLIENT_SEQ.NEXTVAL, 'Ionescu', 'Mihai', 'Brasov', 'ionescu.m@yahoo.com', 'mihai009', 'fgdsd34wd');
INSERT INTO CLIENT VALUES(ID_CLIENT_SEQ.NEXTVAL, 'Popescu', 'Stefan', 'Brasov', 'popescu.s@gmail.com', 'popstef56', 'xsdfsas45');
INSERT INTO CLIENT VALUES(ID_CLIENT_SEQ.NEXTVAL, 'Necula', 'Daniela', 'Timisoara', 'necula.d@gmail.com', 'danyy23', 'weferh33e');
INSERT INTO CLIENT VALUES(ID_CLIENT_SEQ.NEXTVAL, 'Dumitrescu', 'Ioana', 'Bucuresti', 'dumi.i@yahoo.com', NULL, NULL);
INSERT INTO CLIENT VALUES(ID_CLIENT_SEQ.NEXTVAL, 'Enache', 'Maria', 'Iasi', 'enache.m@gmail.com', NULL, NULL);

INSERT INTO FIRMA_CURIERAT VALUES(ID_CURIER_SEQ.NEXTVAL, 'Brasov', 'Fan Curier', '0713456351');
INSERT INTO FIRMA_CURIERAT VALUES(ID_CURIER_SEQ.NEXTVAL, 'Bucuresti', 'Sameday', '0732835675');
INSERT INTO FIRMA_CURIERAT VALUES(ID_CURIER_SEQ.NEXTVAL, 'Iasi', 'Econt', '0721356438');
INSERT INTO FIRMA_CURIERAT VALUES(ID_CURIER_SEQ.NEXTVAL, 'Timisoara', 'Fan Curier', '0752465164');

INSERT INTO COMANDA VALUES(ID_COMANDA_SEQ.NEXTVAL, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('21/12/2021', 'DD/MM/YYYY'), 275, NULL, 1050, 2000);
INSERT INTO COMANDA VALUES(ID_COMANDA_SEQ.NEXTVAL, TO_DATE('01/01/2021', 'DD/MM/YYYY'), TO_DATE('05/01/2021', 'DD/MM/YYYY'), 300, NULL, 1000, 2000);
INSERT INTO COMANDA VALUES(ID_COMANDA_SEQ.NEXTVAL, TO_DATE('12/01/2022', 'DD/MM/YYYY'), TO_DATE('17/01/2022', 'DD/MM/YYYY'), 150, 'Daca nu raspunde nimeni la usa, puteti lasa comanda in fata casei', 1150, 2035);
INSERT INTO COMANDA VALUES(ID_COMANDA_SEQ.NEXTVAL, TO_DATE('22/11/2021', 'DD/MM/YYYY'), TO_DATE('30/11/2021', 'DD/MM/YYYY'), 55, NULL, 1100, 2105);
INSERT INTO COMANDA VALUES(ID_COMANDA_SEQ.NEXTVAL, TO_DATE('25/04/2021', 'DD/MM/YYYY'), TO_DATE('30/04/2021', 'DD/MM/YYYY'), 450, NULL, 1050, 2000);

INSERT INTO FACTURA_FISCALA VALUES(ID_FACTURA_SEQ.NEXTVAL, 'RO1425642574', 'Continental Hotels', 'Brasov', 3000);
INSERT INTO FACTURA_FISCALA VALUES(ID_FACTURA_SEQ.NEXTVAL, 'RO5355134765', 'UTI Holdings', 'Timisoara', 3075);
INSERT INTO FACTURA_FISCALA VALUES(ID_FACTURA_SEQ.NEXTVAL, 'RO2134356539', 'Apulum', 'Bucuresti', 3050);

INSERT INTO DISTRIBUITOR VALUES(ID_DISTRIBUITOR_SEQ.NEXTVAL, 'Bucuresti', 'BijuWorld SRL', '0783742341');
INSERT INTO DISTRIBUITOR VALUES(ID_DISTRIBUITOR_SEQ.NEXTVAL, 'Ploiesti', 'RedBox Jewel', '0743243139');
INSERT INTO DISTRIBUITOR VALUES(ID_DISTRIBUITOR_SEQ.NEXTVAL, 'Alba Iulia', 'Jewelry by Mihaela', '0726525621');

INSERT INTO CATEGORIE VALUES(ID_MATERIAL_SEQ.NEXTVAL, 'Aur');
INSERT INTO CATEGORIE VALUES(ID_MATERIAL_SEQ.NEXTVAL, 'Argint');

INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Inel argint piatra lunii', 100, NULL, 3000, 5000, 6050);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Colier placat cu aur', 175, 24, 3000, 5050, 6000);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Bratara argint pietre semipretioase', 150, NULL, 3050, 5100, 6050);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Inel aur alb', 200, 14, NULL, 5100, 6000);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Cercei argint dimante', 100, NULL, 3025, 5050, 6050);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Bratara aur roz', 100, NULL, 3025, 5000, 6000);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Colier argint gros', 100, NULL, 3025, 5050, 6050);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Cercei argint perle', 55, NULL, 3075, 5100, 6050);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Inel argint pietre swarovski', 400, NULL, 3100, 5050, 6050);
INSERT INTO PRODUS VALUES(ID_BIJUTERIE_SEQ.NEXTVAL, 'Inel aur gravat', 50, 18, 3100, 5050, 6050);
